<?php
// backend/LifeController.php
require_once 'BaseController.php';

class LifeController extends BaseController {

    public function handleRequest($method, $id = null, $action = null) {
        $this->authenticate();

        if ($method === 'GET' && $id === 'today') {
            $this->getTodayLogs();
        } elseif ($method === 'POST' && $id && $action === 'check') {
            $this->checkItem($id);
        } else {
            $this->sendError(404, 'Endpoint Not Found');
        }
    }

    /**
     * Get IDs of items checked today
     */
    private function getTodayLogs() {
        if (!$this->currentUserId) {
            $this->sendError(401, 'User context required');
        }

        // SQLite 'active' date logic. Simple local time of server usually.
        // Ideally should accept timezone or date parameter?
        // Let's rely on server time 'start of day' for now.
        
        $sql = "
            SELECT item_id 
            FROM life_logs 
            WHERE user_id = ? 
            AND date(datetime(checked_at, 'unixepoch', 'localtime')) = date('now', 'localtime')
        ";
        // Wait, life_logs.checked_at is created with strftime('%s', 'now') which is UNIX TIMESTAMP (INTEGER).
        // SQLite: datetime(TS, 'unixepoch') returns string.
        
        // Simpler: Just get log from last 24h? No, strictly "Today".
        // Let's match by YYYY-MM-DD generated by PHP to be safe from TZ mismatch if PHP TZ differs.
        
        // Re-impl: Accept date query param, default to today.
        $targetDate = $_GET['date'] ?? date('Y-m-d');
        
        // We stored as INTEGER timestamp.
        // Filter by Range: start of day to end of day.
        $start = strtotime("$targetDate 00:00:00");
        $end = strtotime("$targetDate 23:59:59");
        
        $stmt = $this->pdo->prepare("SELECT item_id FROM life_logs WHERE user_id = ? AND checked_at BETWEEN ? AND ?");
        $stmt->execute([$this->currentUserId, $start, $end]);
        
        $itemIds = $stmt->fetchAll(PDO::FETCH_COLUMN);
        
        // Return object keys for easy frontend lookup? Or just list.
        // Frontend expects: { "id1": true, "id2": true }
        $result = [];
        foreach ($itemIds as $iid) {
            $result[$iid] = true;
        }
        
        $this->sendJSON($result);
    }

    /**
     * Toggle Check
     */
    private function checkItem($itemId) {
        if (!$this->currentUserId) {
            $this->sendError(401, 'User context required');
        }

        $targetDate = date('Y-m-d');
        $start = strtotime("$targetDate 00:00:00");
        $end = strtotime("$targetDate 23:59:59");

        try {
            $this->pdo->beginTransaction();

            // Check existence
            $stmt = $this->pdo->prepare("
                SELECT id FROM life_logs 
                WHERE user_id = ? AND item_id = ? AND checked_at BETWEEN ? AND ?
            ");
            $stmt->execute([$this->currentUserId, $itemId, $start, $end]);
            $existing = $stmt->fetch(PDO::FETCH_ASSOC);

            if ($existing) {
                // DELETE (Uncheck)
                $del = $this->pdo->prepare("DELETE FROM life_logs WHERE id = ?");
                $del->execute([$existing['id']]);
                $this->pdo->commit();
                $this->sendJSON(['success' => true, 'checked' => false]);
            } else {
                // INSERT (Check)
                $ins = $this->pdo->prepare("INSERT INTO life_logs (user_id, item_id, checked_at) VALUES (?, ?, ?)");
                $ins->execute([$this->currentUserId, $itemId, time()]);
                $this->pdo->commit();
                $this->sendJSON(['success' => true, 'checked' => true]);
            }

        } catch (PDOException $e) {
            $this->pdo->rollBack();
            $this->sendError(500, 'Database Error: ' . $e->getMessage());
        }
    }
}
